### Definir a variável token
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEzLCJlbWFpbCI6ImVyYXNtbzEwMUBnbWFpbC5jb20iLCJpYXQiOjE3MzMzNzUyOTIsImV4cCI6MTczMzM3ODg5Mn0.Mo2qkhuQu1x__9SZOm1G3T5MzrIXLlGqvv8NxAybeYk

### login

POST http://localhost:3000/users/login
Content-Type: application/json

{
   "email": "erasmo101@gmail.com",
   "password": "mestre1234"
}

### Teste de Criação de Usuário
POST http://localhost:3000/users/create
Content-Type: application/json

{
  "name": "Erasmo Cardoso",
  "email": "erasmo101@gmail.com",
  "whatsapp": "119492243553",
  "password": "mestre1234"
}

### Teste para Obter Todos os Usuários
GET http://localhost:3000/users/buscar
Authorization: Bearer {{token}}

### Teste para Obter um Usuário por ID
GET http://localhost:3000/users/buscar/13
Authorization: Bearer {{token}}

### Teste de Atualização de Usuário
PUT http://localhost:3000/users/atualizar/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Erasmo Silva atualiza",
  "email": "atualiza1-erasmo.silva@example.com",
  "whatsapp": "11949224355",
  "password": "senha456 atualiza"
}

### Teste de Exclusão de Usuário
DELETE http://localhost:3000/users/deleta/47
Authorization: Bearer {{token}}
